
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.
#

fibonacci = []
x = 4000000

x.times do
  if fibonacci.size == 0 || fibonacci.size == 1
    fibonacci << 1
  else
    fibonacci << fibonacci[-2] + fibonacci[-1]
  end
end

p fibonacci.select {|num| num.even? }.reduce(:+)


